Namespace(cuda=True, directory='program_data/cpp_babi_format_Sep-29-2018-0000008', is_training_ggnn=True, log_path='program_data/cpp_babi_format_Sep-29-2018-0000008/logs', lr=0.01, manualSeed=0, model_path='program_data/cpp_babi_format_Sep-29-2018-0000008/cpp_babi_format_Sep-29-2018-0000008-104.cpkl', n_classes=104, n_hidden=50, n_steps=5, niter=150, size_vocabulary=198, state_dim=5, test_batch_size=32, testing=False, train_batch_size=128, training=True, training_percentage=1.0, verbal=True, workers=2)
Random Seed:  0
Number of all training data : 34627
Max node id : 192
Number of all testing data : 17367
Max node id : 197
Using the saved model....
/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py:365: UserWarning: ONNX export failed on ATen operator stack because torch.onnx.symbolic.stack does not exist
  .format(op_name, op_name))
/opt/conda/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py:43: UserWarning: Error getting attributes of node %118 : Dynamic = onnx::Constant[value={1}](), scope: GGNN/Propogator[propogator], error is VariableType::ID() not implemented
  warnings.warn("Error getting attributes of node {}, error is {}".format(attrs, e))
/opt/conda/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py:43: UserWarning: Error getting attributes of node %193 : Dynamic = onnx::Constant[value={1}](), scope: GGNN/Propogator[propogator], error is VariableType::ID() not implemented
  warnings.warn("Error getting attributes of node {}, error is {}".format(attrs, e))
/opt/conda/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py:43: UserWarning: Error getting attributes of node %268 : Dynamic = onnx::Constant[value={1}](), scope: GGNN/Propogator[propogator], error is VariableType::ID() not implemented
  warnings.warn("Error getting attributes of node {}, error is {}".format(attrs, e))
/opt/conda/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py:43: UserWarning: Error getting attributes of node %343 : Dynamic = onnx::Constant[value={1}](), scope: GGNN/Propogator[propogator], error is VariableType::ID() not implemented
  warnings.warn("Error getting attributes of node {}, error is {}".format(attrs, e))
/opt/conda/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py:43: UserWarning: Error getting attributes of node %418 : Dynamic = onnx::Constant[value={1}](), scope: GGNN/Propogator[propogator], error is VariableType::ID() not implemented
  warnings.warn("Error getting attributes of node {}, error is {}".format(attrs, e))
[0/150][0/271] Loss: 4.1879
[0/150][28/271] Loss: 4.1419
[0/150][56/271] Loss: 4.1888
[0/150][84/271] Loss: 4.1819
[0/150][112/271] Loss: 4.1684
[0/150][140/271] Loss: 4.0792
[0/150][168/271] Loss: 4.1666
[0/150][196/271] Loss: 4.1785
[0/150][224/271] Loss: 4.2134
[0/150][252/271] Loss: 4.2032
Test set: Average loss: 0.1327, Accuracy: 7273/17367 (41%)
[1/150][0/271] Loss: 4.1423
[1/150][28/271] Loss: 4.2289
[1/150][56/271] Loss: 4.2235
[1/150][84/271] Loss: 4.1889
[1/150][112/271] Loss: 4.1631
[1/150][140/271] Loss: 4.2009
[1/150][168/271] Loss: 4.2124
[1/150][196/271] Loss: 4.1991
[1/150][224/271] Loss: 4.1781
[1/150][252/271] Loss: 4.2064
Test set: Average loss: 0.1327, Accuracy: 7291/17367 (41%)
[2/150][0/271] Loss: 4.2331
[2/150][28/271] Loss: 4.2765
[2/150][56/271] Loss: 4.2099
[2/150][84/271] Loss: 4.1820
[2/150][112/271] Loss: 4.1888
[2/150][140/271] Loss: 4.1708
[2/150][168/271] Loss: 4.2336
[2/150][196/271] Loss: 4.1966
[2/150][224/271] Loss: 4.2633
[2/150][252/271] Loss: 4.1779
Test set: Average loss: 0.1327, Accuracy: 7269/17367 (41%)
[3/150][0/271] Loss: 4.2394
[3/150][28/271] Loss: 4.1885
[3/150][56/271] Loss: 4.2363
[3/150][84/271] Loss: 4.1801
[3/150][112/271] Loss: 4.1607
[3/150][140/271] Loss: 4.1861
[3/150][168/271] Loss: 4.2427
[3/150][196/271] Loss: 4.2193
[3/150][224/271] Loss: 4.2223
[3/150][252/271] Loss: 4.2500
Test set: Average loss: 0.1329, Accuracy: 7163/17367 (41%)
[4/150][0/271] Loss: 4.2001
[4/150][28/271] Loss: 4.2596
[4/150][56/271] Loss: 4.1817
[4/150][84/271] Loss: 4.2010
[4/150][112/271] Loss: 4.1807
[4/150][140/271] Loss: 4.2119
[4/150][168/271] Loss: 4.1956
[4/150][196/271] Loss: 4.2224
[4/150][224/271] Loss: 4.2093
[4/150][252/271] Loss: 4.1777
Test set: Average loss: 0.1328, Accuracy: 7221/17367 (41%)
[5/150][0/271] Loss: 4.1321
[5/150][28/271] Loss: 4.1905
[5/150][56/271] Loss: 4.2879
[5/150][84/271] Loss: 4.1911
[5/150][112/271] Loss: 4.1931
[5/150][140/271] Loss: 4.1952
[5/150][168/271] Loss: 4.2460
[5/150][196/271] Loss: 4.2279
[5/150][224/271] Loss: 4.2229
[5/150][252/271] Loss: 4.1910
^CProcess Process-22:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 52, in _worker_loop
    r = index_queue.get()
  File "/opt/conda/lib/python3.6/multiprocessing/queues.py", line 335, in get
    res = self._reader.recv_bytes()
  File "/opt/conda/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/opt/conda/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/opt/conda/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
Traceback (most recent call last):
  File "main_ggnn.py", line 102, in <module>
    main(opt)
  File "main_ggnn.py", line 93, in main
    train(epoch, train_dataloader, net, criterion, optimizer, opt, writer)
  File "/e/utils/train_ggnn.py", line 17, in train
    adj_matrix = adj_matrix.cuda()
KeyboardInterrupt
(41%)
(41%)
(41%)
(41%)
(41%)
